notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: TP0n75stsNtM+KEzpE35uwxliRHVzZVs37cWcdllmS5LAiERqm2zMRzsNH2A5RrSsYYO9on+NQ/Z4BjaiJJu589fI/OMNNmw2r4Aln58uS46HI8HMMIj0VXKJIa+iMgIGucHiEuP06Z4C0F8C7/vjIMyfA5DxOFTYU6fY7PtHnD8sNUhdqoQt5Rw6hwB8nOfh+4S00W4AlWTgbOQdwUiVdGkEvNUBONH4hU0QbQYW5DNw+lldWpq7KExejXektV0enRGVGskX3U92Q70Yxk+SRxou0VrnnjJv7sVcmr6UDfZ021N155wLu9dirFh8cjuwXIbPZMJIUAOFpr1QmU1Pix49a1mDxklpqPmdTo/VwHdwE8aD8tRXt2uh8wnXrNL7pDaOzNvn/uWRxaKi4y0qT2I8JNyyiESeFEXPCwYQzhwY9SuNtkDFfMQw48O+6xRPJoCQJY0UO/EX3TN7ry5GjFlwogM1ugOGk+7pks1/lthTNQkkYnqvtFcUl02TfzklDZA1aDz/kNn3tdGjdL0IflsJFjjvAipZYcZWq+7/RMuSjq4MP4J2ANfV3Dr9mK2sOqkhQfyW6CcGhUn9vuhe3H/dQvwfejWTjyPew1//JlBeBytdGxtTPuzfcvGhx4U46qDEvtKkRkVtapYTa4M8d6MXp1z9YTIxwjDeiu586Y=
  api_key:
    secure: vBF5j5DBV4jnwixFMdLYsQfB6YxEhzSFOQLrxmAZD+i3fT/BW0Ngtryshso0hwhb97CsDEpqIVGMOVCRj40ZlpgnUOWcoBC8idpxA82Oms48APGkOfOFddr/ET0SK4Tv/W8hhE0G2KPEk8ay+IdnIjvMXQFcIdeF6XFyYgOf5fV9Du9M3H/1aAseg3wiP7yNnt1B/iMiRdewNe7RQ0P65tV0qTajW4uUDHDbyfPhyt4SzKXKTlk40ybNWnO8XGw8jPhXsCjWudJbS12NSYM34g1fJPfQ/mn9aQd3VcE3vVchFPwUV2V+6RrbFCVK7UU55nlohfNDC4w0fw1R9sYwjhL8J8OlSnrx4Hw8tagbO/gWVawg/eaQKqPg6Bbcoacbp6BFVNOKTOoVRbs+HG9tpTAStEyv7HfNIAWX+f7d7R4oZR6UoSM+ZyDCrk9x8bGa1HYAh1Ve0nfU0lndDP50vQW7V8ijjX9Um6/NpyUM5tv4tTl1zsI3xYSCb0MIjvAdwVr9pudU/D+smiR9Y473n0MT4kquSOMvquZYtkY+cwa0G4egiH5zCtWSBO+dZxLGJoAhfBQjRpUipJVY9fInRa0U/5somgiop2ggVgmfv1PKnUbVLplYwGLZIOgmYUbNVQ3bUbi7j1mgLwuDHfHjy/kPUP5P0SqhzQQf0KLXGR8=
  on:
    tags: true
